const { URL } = require('url');

function normalizeServerUrl(value) {
  let url=String(value||'').trim();
  if (!url) throw new Error('Enter the Zaxis server URL.');
  if (!/^https?:\/\//i.test(url)) url='https://'+url;
  const parsed=new URL(url);
  if (!parsed.hostname) throw new Error('Enter a valid Zaxis server URL.');
  return parsed.origin;
}

async function requestJson(url, options={}, timeoutMs=15000) {
  const controller=new AbortController();
  const timer=setTimeout(()=>controller.abort(),timeoutMs);
  try {
    const res=await fetch(url,{
      ...options,
      signal:controller.signal,
      headers:{'Accept':'application/json','Content-Type':'application/json',...(options.headers||{})}
    });
    const text=await res.text();
    let data={};
    if (text) {
      try { data=JSON.parse(text); } catch { data={message:text.slice(0,500)}; }
    }
    if (!res.ok) throw new Error(data.message||data.error||`HTTP ${res.status}`);
    return data;
  } catch(err) {
    if (err.name==='AbortError') throw new Error('Connection timed out.');
    throw err;
  } finally { clearTimeout(timer); }
}

class ZaxisClient {
  constructor({getConnection,getToken,appVersion,systemInfo}) {
    this.getConnection=getConnection;
    this.getToken=getToken;
    this.appVersion=appVersion;
    this.systemInfo=systemInfo;
  }

  authHeaders() {
    const token=this.getToken();
    return token ? {Authorization:`Bearer ${token}`} : {};
  }

  async ping(serverUrl) {
    const server=normalizeServerUrl(serverUrl);
    return requestJson(`${server}/api/workers/ping`,{method:'GET'});
  }

  async pair({serverUrl,workerName,pairingCode,deviceId,capabilities}) {
    const server=normalizeServerUrl(serverUrl);
    const code=String(pairingCode||'').trim();
    if (!code) throw new Error('Enter the pairing code generated by Zaxis Admin.');
    const name=String(workerName||'').trim();
    if (!name) throw new Error('Enter a worker name.');
    const data=await requestJson(`${server}/api/workers/pair`,{
      method:'POST',
      body:JSON.stringify({
        pairingCode:code,
        workerName:name,
        deviceId,
        appVersion:this.appVersion(),
        platform:this.systemInfo(),
        capabilities
      })
    });
    if (!data.workerId || !data.token) throw new Error('Zaxis server returned an invalid pairing response.');
    return {...data,serverUrl:server};
  }

  async heartbeat(payload={}) {
    const c=this.getConnection();
    if (!c?.workerId) throw new Error('Worker is not paired.');
    return requestJson(`${c.serverUrl}/api/workers/${encodeURIComponent(c.workerId)}/heartbeat`,{
      method:'POST',
      headers:this.authHeaders(),
      body:JSON.stringify(payload)
    },10000);
  }

  async nextJob() {
    const c=this.getConnection();
    if (!c?.workerId) return null;
    const data=await requestJson(`${c.serverUrl}/api/workers/${encodeURIComponent(c.workerId)}/jobs/next`,{
      method:'GET',
      headers:this.authHeaders()
    },12000);
    return data.job||null;
  }

  async acceptJob(remoteJobId) {
    const c=this.getConnection();
    return requestJson(`${c.serverUrl}/api/workers/jobs/${encodeURIComponent(remoteJobId)}/accept`,{
      method:'POST',headers:this.authHeaders(),body:JSON.stringify({workerId:c.workerId})
    });
  }

  async progress(remoteJobId,payload) {
    const c=this.getConnection();
    return requestJson(`${c.serverUrl}/api/workers/jobs/${encodeURIComponent(remoteJobId)}/progress`,{
      method:'POST',headers:this.authHeaders(),body:JSON.stringify({...payload,workerId:c.workerId})
    },10000);
  }

  async uploadResults(remoteJobId,payload) {
    const c=this.getConnection();
    return requestJson(`${c.serverUrl}/api/workers/jobs/${encodeURIComponent(remoteJobId)}/results`,{
      method:'POST',headers:this.authHeaders(),body:JSON.stringify({...payload,workerId:c.workerId})
    },30000);
  }

  async completeJob(remoteJobId,payload={}) {
    const c=this.getConnection();
    return requestJson(`${c.serverUrl}/api/workers/jobs/${encodeURIComponent(remoteJobId)}/complete`,{
      method:'POST',headers:this.authHeaders(),body:JSON.stringify({...payload,workerId:c.workerId})
    });
  }

  async failJob(remoteJobId,payload={}) {
    const c=this.getConnection();
    return requestJson(`${c.serverUrl}/api/workers/jobs/${encodeURIComponent(remoteJobId)}/fail`,{
      method:'POST',headers:this.authHeaders(),body:JSON.stringify({...payload,workerId:c.workerId})
    });
  }
}

module.exports={ZaxisClient,normalizeServerUrl,requestJson};
